<script>
	// @ts-nocheck
	import { onMount } from 'svelte';
	import Header from '$lib/components/Header.svelte'; import Footer from '$lib/components/Footer.svelte';
	const projects=[['Business Signs','business-sign.png','Wall signs, office branding & displays'],['Custom Cutting & Engraving','custom-cutting.png','Precision-made for your idea'],['Weddings & Events','wedding-acrylic.png','Details that make an occasion yours'],['Home Decor','home-decor.png','Warm, personal pieces for everyday spaces'],['I Have a File Ready','file-ready.png','Send your artwork and get started']];
	let project=$state(''); function choose(name){project=name; setTimeout(()=>document.querySelector('#quote')?.scrollIntoView({behavior:'smooth'}),0)}
	onMount(() => {
		const form = document.querySelector('.quote-form'); const firstFile = form?.querySelector('input[name="attachment_1"]'); if (!form || !firstFile) return;
		const holder = firstFile.closest('label'); const stored = [firstFile];
		for (const number of [2,3]) { const input=document.createElement('input'); input.type='file'; input.name=`attachment_${number}`; input.accept=firstFile.accept; stored.push(input); form.append(input); }
		form.append(firstFile); stored.forEach((input) => input.className='stored-file');
		const zone=document.createElement('section'); zone.className='file-drop'; zone.tabIndex=0; zone.innerHTML='<div aria-hidden="true" class="upload-icon">↥</div><strong>Drop your design files here</strong><span>or click to browse — up to 3 files, 8 MB total</span><small>PDF, AI, EPS, SVG, DXF, DWG, PNG, JPG, WEBP or ZIP</small>';
		const picker=document.createElement('input'); picker.type='file'; picker.multiple=true; picker.accept=firstFile.accept; picker.hidden=true; zone.append(picker); holder?.replaceWith(zone);
		const subject=document.createElement('input'); subject.type='hidden'; subject.name='subject'; subject.value='New ANP Cutting quote request'; form.append(subject);
		const choices=document.createElement('div'); choices.innerHTML='<div class="choice-row"><fieldset><legend>Is your design or file ready?</legend><label><input required type="radio" name="file_ready" value="Yes" /> Yes</label><label><input required type="radio" name="file_ready" value="No" /> No</label></fieldset><fieldset><legend>Preferred turnaround</legend><label><input required type="radio" name="turnaround" value="Standard (5 to 7 Days)" /> Standard (5–7 days)</label><label><input required type="radio" name="turnaround" value="Fast (2 to 3 Days)" /> Fast (2–3 days)</label><label><input required type="radio" name="turnaround" value="Urgent (24 to 48 Hours)" /> Urgent (24–48 hours)</label></fieldset></div><label>How did you hear about us?<select name="referral_source"><option value="">Select an option</option><option>Google</option><option>Facebook</option><option>Instagram</option><option>Referral</option><option>ChatGPT or another AI assistant</option><option>Other</option></select></label>';
		form.insertBefore(choices, zone);
		const status=document.createElement('p'); status.className='form-note'; zone.after(status);
		const assign=(list) => { const files=[...list]; const total=files.reduce((sum,file)=>sum+file.size,0); if(!files.length){status.textContent='';return;} if(files.length>3||total>8*1024*1024){status.textContent='Please attach no more than 3 files, with a combined size of 8 MB or less.'; picker.value=''; return;} stored.forEach((input,index)=>{const data=new DataTransfer(); if(files[index]) data.items.add(files[index]); input.files=data.files;}); status.textContent=`${files.length} file${files.length===1?'':'s'} ready to send: ${files.map(file=>file.name).join(', ')}`; };
		picker.addEventListener('change',()=>assign(picker.files)); zone.addEventListener('click',()=>picker.click()); zone.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();picker.click();}}); zone.addEventListener('dragover',(event)=>{event.preventDefault();zone.classList.add('is-dragging')}); zone.addEventListener('dragleave',()=>zone.classList.remove('is-dragging')); zone.addEventListener('drop',(event)=>{event.preventDefault();zone.classList.remove('is-dragging');assign(event.dataTransfer.files)});
		const submit = async (event) => { event.preventDefault(); status.textContent = 'Sending your request…'; try { const response = await fetch('/__forms.html', { method: 'POST', body: new FormData(form) }); if (response.ok) window.location.assign('/thanks'); else throw new Error('Submission failed'); } catch { status.textContent = 'We could not send your request. Please try again or email info@anpcutting.com.'; } };
		form.addEventListener('submit', submit); return () => form.removeEventListener('submit', submit);
	});
</script>
<svelte:head><title>ANP Cutting | Custom Laser Cutting, CNC & Engraving</title><meta name="description" content="Custom laser cutting, CNC routing, engraving, signage and decor in Mississauga." /></svelte:head>
<Header />
<main id="top"><section class="hero"><img class="hero-image" src="/assets/projects/hero-wood-lattice.png" alt="Custom walnut lattice and layered wood sign detail" /><div class="hero-copy"><p class="eyebrow">Custom cutting & engraving in Mississauga</p><h1>What would you like to create?</h1><p class="hero-text">From a rough idea to a precision-made piece, ANP Cutting creates custom signs, decor, event details and fabrication projects.</p><div class="hero-actions"><a class="button button-primary" href="#quote">Request a Quote</a><a class="text-link" href="#projects">Explore Our Work →</a></div></div></section>
<section class="project-picker" id="projects"><div class="section-intro"><p class="eyebrow">Start with your goal</p><h2>Choose the path that fits your project.</h2></div><div class="project-grid">{#each projects as item}<button class="project-card" onclick={() => choose(item[0])}><img src={'/assets/projects/'+item[1]} alt={item[0]} /><span><strong>{item[0]}</strong><small>{item[2]}</small></span></button>{/each}</div></section>
<aside class="quote-strip"><p>Not sure which service you need?</p><a class="button button-dark" href="#quote">Request a Quote</a></aside>
<section class="services" id="services"><div><p class="eyebrow">Built for ideas of every scale</p><h2>Precision services.<br />Personal guidance.</h2></div><div class="service-list"><article><b>01</b><h3>Laser Cutting & Engraving</h3><p>Ideal for precise details, sharp corners, custom engraving and smaller cut pieces.</p></article><article><b>02</b><h3>CNC Routing</h3><p>Built for larger panels, thicker material, wall decor, signage and architectural work.</p></article><article><b>03</b><h3>Edge Banding</h3><p>Clean, durable finishing for plywood, MDF, cabinetry, shelving, and custom panels.</p></article></div></section>
<section class="materials"><p class="eyebrow">Materials we work with</p><div><span>Wood</span><span>Acrylic</span><span>PVC</span><span>Alupanel</span></div></section>
<section class="process" id="process"><div class="section-intro"><p class="eyebrow">Clear from start to finish</p><h2>Your idea, precision-made.</h2></div><ol><li><b>1</b><h3>Share your idea</h3><p>Send a file, sketch, image or short description.</p></li><li><b>2</b><h3>Design & quote</h3><p>We help refine the details and prepare a quote.</p></li><li><b>3</b><h3>We make it</h3><p>Your piece is cut, engraved and finished with care.</p></li><li><b>4</b><h3>Pick up or deliver</h3><p>We’ll let you know as soon as it is ready.</p></li></ol></section>
<section class="gallery"><img src="/assets/projects/portfolio-divider.png" alt="Custom walnut room divider" /><img src="/assets/projects/portfolio-gifts.png" alt="Walnut keepsake boxes" /><img src="/assets/projects/portfolio-acrylic.png" alt="Clear acrylic display plaque" /><img src="/assets/projects/portfolio-address.png" alt="Layered address sign" /></section>
<section class="about" id="about"><div><p class="eyebrow">Since 2016</p><h2>Custom work should feel easy to order.</h2></div><p>ANP Cutting began with a curiosity for laser and CNC cutting and grew into a practical, flexible custom fabrication business. Whether you know exactly what you need or only have an idea, we’ll help you find a way forward.</p></section>
<section class="quote quote-expanded" id="quote"><div><p class="eyebrow">Let’s make it</p><h2>Tell us about your project.</h2><p>Share your idea, approximate dimensions, material preference, deadline, and any reference photos.</p></div><form class="quote-form" name="quote-request" method="POST" action="/thanks" data-netlify="true" netlify-honeypot="bot-field" enctype="multipart/form-data"><input type="hidden" name="form-name" value="quote-request" /><p class="honeypot"><label>Don’t fill this out <input name="bot-field" /></label></p><div class="form-grid"><label>Name <input required name="name" /></label><label>Company name<input name="company" /></label><label>Phone <input required type="tel" name="phone" /></label><label>Email <input required type="email" name="email" /></label><label>Project type<select required name="project_type" bind:value={project}><option value="" disabled>Select an option</option>{#each projects as item}<option>{item[0]}</option>{/each}<option>Laser Cutting</option><option>CNC Cutting</option><option>Engraving</option><option>Custom Request</option></select></label><label>Material choice<select name="material"><option>Wood</option><option>Acrylic</option><option>PVC</option><option>Alupanel</option><option>Other / custom</option></select></label></div><label>Project details <textarea required name="project_details" rows="5"></textarea></label><label>File <input type="file" name="attachment_1" accept=".pdf,.ai,.eps,.svg,.dxf,.dwg,.png,.jpg,.jpeg,.webp,.zip" /></label><button class="button button-primary" type="submit">Send Quote Request</button></form></section></main><Footer />
